spring:
  application.name: product
  datasource:
    url: jdbc:mysql://localhost:3306/products
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9090
  error:
    include-message: always